# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"testme": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://muellerzr.github.io/your_lib/"

git_url = "https://github.com/muellerzr/your_lib/tree/{branch}/"

def custom_doc_links(name): return None
