# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {}

modules = []

doc_url = "https://muellerzr.github.io/your_project_name/"

git_url = "https://github.com/muellerzr/your_project_name/tree/{branch}/"

def custom_doc_links(name): return None
